backend/models/Team.php
<?php

namespace backend\models;

use Yii;
use yii\db\ActiveRecord;


/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 * @property string $coach
 * @property int $league_id
 * @property string $stadium
 * @property string $capacity
 * @property string $town
 * @property float $value
 *  @property string $league_name
 */
class Team extends ActiveRecord
{

    public $points;
    public $goals_scored;
    public $goals_conceded;
    public $balance;
    public $league_name;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'team';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'coach', 'stadium', 'capacity', 'town', 'value'], 'required'],
            [['league_id'], 'integer'],
            [['value', 'capacity'], 'number'],
            [['name', 'coach', 'stadium', 'capacity', 'town', 'league_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'coach' => 'Coach',
            'league_id' => 'League ID',
            'stadium' => 'Stadium',
            'capacity' => 'Capacity',
            'town' => 'Town',
            'value' => 'Value',
            'league_name' => 'League Name'
        ];
    }
}

frontend/models/Team.php
<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;
use yii\base\Model;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 * @property string $coach
 * @property int $league_id
 * @property string $stadium
 * @property string $capacity
 * @property string $town
 * @property float $value
 */
class Team extends ActiveRecord
{

    public $points;
    public $goals_scored;
    public $goals_conceded;
    public $balance;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'team';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'coach', 'stadium', 'capacity', 'town', 'value'], 'required'],
            [['league_id'], 'integer'],
            [['value', 'capacity'], 'number'],
            [['name', 'coach', 'stadium', 'capacity', 'town'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'coach' => 'Coach',
            'league_id' => 'League ID',
            'stadium' => 'Stadium',
            'capacity' => 'Capacity',
            'town' => 'Town',
            'value' => 'Value',
        ];
    }
}

backend/controllers/TeamController.php
<?php

namespace backend\controllers;

use backend\models\League;
use Yii;
use backend\models\Team;
use backend\models\TeamSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TeamController implements the CRUD actions for Team model.
 */
class TeamController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Team models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TeamSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Team model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Team model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Team();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Team model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $leagueQuery = Team::find()->select(['league_id'])->orderBy('league_id')->all();
        $leagueList = ArrayHelper::map($leagueQuery, 'league_id', 'league_id');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'leagueList' => $leagueList
        ]);
    }

    /**
     * Deletes an existing Team model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Team model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Team the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Team::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/TeamController.php
<?php

namespace frontend\controllers;

use frontend\models\League;
use frontend\models\Match;
use frontend\models\MatchDay;
use frontend\models\Team;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


/**
 * Team controller
 */
class TeamController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
//                'only' => ['team'],
                'rules' => [
                    [
                        'actions' => ['detail', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    public function actionDetail($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $team = Team::find()->where(['league_id' => $id])->orderBy('league_id');
        $teams = Team::find()->where(['league_id' => $id])->all();
        $league = League::find()->where(['id' => $id])->orderBy('id')->one();
        $user_id = Yii::$app->user->id;

        $match_day_last = MatchDay::find()->where(['league_id' => $id])->orderBy('number DESC')->one();

        $new_team = new Team;
        if ($new_team->load(Yii::$app->request->post()) && $new_team->validate()) {
            $new_team->league_id = $id;
            $new_team->save();
            return $this->refresh();
        }

        $teamList = ArrayHelper::map($teams, 'id', 'name');

        $dataProvider = new ActiveDataProvider(['query' => $team]);

        if ($id == $user_id) {
            return $this->render('myteam',
                [
                    'team' => $team,
                    'teamList' => $teamList,
                    'league' => $league,
                    'new_team' => $new_team,
                    'match_day_last' => $match_day_last,
                    'dataProvider' => $dataProvider
                ]);
        }
        return $this->render('detail', [
                'team' => $team,
                'league' => $league,
                'match_day_last' => $match_day_last,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    public function actionDelete()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $team_id = Yii::$app->request->post('Team');

        $delete_team = Team::find()->where(['id' => $team_id])->one();

        if ($delete_team) {

            $league_id = $delete_team->league_id;
            $delete_match = Match::find()->where(['home_team' => $delete_team->id])->orWhere(['visitor_team' => $delete_team->id])->all();

            foreach ($delete_match as $match) {
                $match->delete();
            }
            $delete_team->delete();

            return $this->redirect(['team/detail', 'id' => $league_id]);
        }
        return $this->goBack();
    }
}

frontend/views/team/detail.php
<?php

/* @var $this yii\web\View */
/* @var $league League */
/* @var $team Team */
/* @var ActiveDataProvider $dataProvider */

/* @var $match_day_last MatchDay */

use frontend\models\League;
use frontend\models\MatchDay;
use frontend\models\Team;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'My Yii Application - League';
?>

<div class="container">
    <div>
        <a href="<?= Url::to(['/']); ?>"><h3><-- Back</h3></a>
        <h1><?= Html::encode("{$league->name}") ?>: 19/20</h1>
        <?= Html::a('Create a match-day -->', ['match-day/add', 'id' => $league->id], ['class' => 'match-day']) ?>
        <?php if ($match_day_last): ?>
            <?= Html::a('Matchdays', ['match-day/matchdays', 'id' => $league->id, 'match_day_id' => $match_day_last->id], ['class' => 'matches']) ?>
        <?php endif ?>
        <?= Html::a('Live table', ['match-day/table', 'id' => $league->id], ['class' => 'match-day match-day--table']) ?>
        <div class="content">
            <?= \yii\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'class' => 'team_table',
                'columns' => [
                    'name',
                    'coach',
                    'stadium',
                    'capacity',
                    'town',
                    'value'
                ],
                'summary' => false,
            ]) ?>
        </div>
    </div>

frontend/views/team/myteam.php
<?php
/* @var $this yii\web\View */
/* @var $league League */
/* @var $team Team */
/* @var $new_team Team */
/* @var $teamList array */
/* @var $delete_team Team */
/* @var ActiveDataProvider $dataProvider */

/* @var $match_day_last MatchDay */

use frontend\models\League;
use frontend\models\MatchDay;
use frontend\models\Team;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'My Yii Application - My Team';
?>

<aside>
    <div class="tools form-group">
        <ul>

            <?php $form = ActiveForm::begin(); ?>
            <li><p class="team_add delete_team_hidden delete_league_hidden">Add team</p>
                <div class="my_team_add">
                    <h5>Add team</h5>
                    <?= $form->field($new_team, 'name')->textInput(['placeholder' => "Team name"])->label(false) ?>

                    <?= $form->field($new_team, 'coach')->textInput(['placeholder' => "Trainer's name"])->label(false) ?>

                    <?= $form->field($new_team, 'stadium')->textInput(['placeholder' => "Stadium"])->label(false) ?>

                    <?= $form->field($new_team, 'capacity')->textInput(['placeholder' => "Capacity", 'type' => 'number', 'max' => 112000, 'min' => 100])->label(false) ?>

                    <?= $form->field($new_team, 'town')->textInput(['placeholder' => "Town"])->label(false) ?>

                    <?= $form->field($new_team, 'value')->textInput(['placeholder' => "Team value", 'type' => 'number', 'max' => 1000, 'min' => 1])->label(false) ?>
                    <?= \yii\helpers\Html::submitButton('Add team!', ['class' => 'btn btn-primary btn_position']) ?>
                </div>
            </li>
            <?php ActiveForm::end() ?>

            <?php $form = ActiveForm::begin(['action' => Url::to(['team/delete'])]); ?>
            <li><p class="team_delete team_add_hidden delete_league_hidden">Delete team</p>
                <div class="my_team_delete">
                    <h5>Delete team</h5>
                    <?= $form->field($new_team, 'id')->dropDownList($teamList)->label(false) ?>
                    <?= \yii\helpers\Html::submitButton('Delete team!', ['class' => 'btn btn-primary btn_position']) ?>
                </div>
            </li>
            <?php ActiveForm::end() ?>

            <?php $form = ActiveForm::begin(['action' => Url::to(['league/delete'])]); ?>
            <li><p class="league_delete team_add_hidden delete_team_hidden">Delete league</p>
                <div class="my_league_delete">
                    <h5>Czy na pewno chcesz usunąć ligę ?</h5>
                    <?= \yii\helpers\Html::activeHiddenInput($league, 'id') ?>
                    <?= \yii\helpers\Html::submitButton('Delete league!', [
                        'class' => 'btn btn-primary btn_position',
                        'data-confirm' => 'Are you sure you want to delete this item?',
                    ]) ?>
                </div>
            </li>
            <?php ActiveForm::end() ?>

        </ul>
    </div>
</aside>

<div class="container">
    <div><a href="<?= Url::to(['/']); ?>"><h3><-- Back</h3></a>
        <h1><?= \yii\helpers\Html::encode("{$league->name}") ?>: 19/20</h1></div>
    <?= Html::a('Create a match-day -->', ['match-day/add', 'id' => $league->id], ['class' => 'match-day']) ?>
    <?php if ($match_day_last): ?>
        <?= Html::a('Matchdays', ['match-day/matchdays', 'id' => $league->id, 'match_day_id' => $match_day_last->id], ['class' => 'matches']) ?>
    <?php endif; ?>
    <?= Html::a('Live table', ['match-day/table', 'id' => $league->id], ['class' => 'match-day match-day--table']) ?>
    <div class="content">
        <?= \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'class' => 'team_table',
            'columns' => [
                'name',
                'coach',
                'stadium',
                'capacity',
                'town',
                'value'
            ],
            'summary' => false,
        ]) ?>
    </div>
</div>