backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\helpers\VarDumper;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect('/advanced/frontend/web/');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\League;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['signup', 'login', 'index', 'logout', 'about', 'contact', 'add-league', 'reset-password', 'request-password-reset', 'verify-email', 'resend-verification-email'],
                'rules' => [
                    [
                        'actions' => ['signup', 'login', 'reset-password', 'request-password-reset', 'verify-email', 'resend-verification-email'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index', 'about', 'contact', 'add-league',],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $league = League::find()->orderBy('name')->all();
        $user = Yii::$app->user;
        $add_league = new League();
        $id = Yii::$app->user->id;
        $user_league = League::find()->where(['user_id' => $id])->all();


        if ($user_league === $id) {
            return $this->redirect(Yii::$app->request->referrer);
        }
        if ($add_league->load(Yii::$app->request->post())) {
            $add_league->img = UploadedFile::getInstance($add_league, 'img');
            $add_league->user_id = Yii::$app->user->id;
            $add_league->id = Yii::$app->user->id;


            if ($add_league->upload()) {
                $add_league->save(false);
                return $this->refresh();
            }
        }

        return $this->render('index',
            [
                'league' => $league,
                'user' => $user,
                'add_league' => $add_league,
            ]
        );

    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = 'logout';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }


    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        $this->layout = 'logout';
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = 'logout';
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'logout';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = 'logout';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @return yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionVerifyEmail($token)
    {
        $this->layout = 'logout';

        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $this->layout = 'logout';
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionAddLeague($id)
    {
//        $league = League::find()->orderBy('name')->all();
        $model = new League();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            return $this->refresh();
        }
    }

    public function actionNews($id)
    {
        return $this->render('news');
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <div><a href="<?= \yii\helpers\Url::to(['login']) ?>"><h3><-- Back</h3></a>
        <p>This is the About page. You may modify the following file to customize its content:</p>
    </div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model ContactForm */

use frontend\models\ContactForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
    <div><a href="<?= \yii\helpers\Url::to(['/'])?>"><h3><-- Back</h3></a>
    <div class="row">
        <div class="login_background col-lg-5">
            <p>
                If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
            </p>
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>
</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

/* @var $add_league League */

use frontend\models\League;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'My Yii Application';
?>
    <div class="newsletter">
        <ol>
            <?php sort($league) ?>
            <?php foreach ($league as $item): ?>
                <?php if ($item->user_id == 0): ?>
                    <li><?= \yii\helpers\Html::encode("{$item->name}") ?>
                        <ul>
                            <li>
                                <a href="<?= Url::to(['site/news']); ?>?id=<?= \yii\helpers\Html::encode("{$item->id}") ?>">News</a>
                            </li>
                            <li><a href="<?= Url::to(['']); ?>?id=<?= \yii\helpers\Html::encode("{$item->id}") ?>">Transfers</a>
                            </li>
                        </ul>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
<div class="container">
    <h1>Choose your league:</h1>
    <div class="content">
        <div class="row leagues">
            <?php sort($league) ?>
            <?php foreach ($league as $item): ?>
                <div class="col-4 league"><a
                            href="<?= Url::to(['/team/detail']); ?>?id=<?= \yii\helpers\Html::encode("{$item->id}") ?>"><img
                                src="../img/<?= $item->img ?>" alt="<?= \yii\helpers\Html::encode("{$item->name}") ?>">
                        <a/></div>
            <?php endforeach; ?>
        </div>
        <div class="row leagues">
            <div class="add_league col-6 offset-3">
                <div class="open"><p>Add own league !</p></div>
                <div class="add_form">
                    <?php $form = ActiveForm::begin(); ?>
                    <label>
                        <?= $form->field($add_league, 'name')->textInput(['placeholder' => "League name"])->label(false) ?>
                        <label>
                            <?= $form->field($add_league, 'img')->fileInput()->label(false) ?>
                        </label>
                        <?= \yii\helpers\Html::submitButton('Add league!', ['class' => 'btn btn-primary btn_position']) ?>
                        <?php \yii\widgets\ActiveForm::end() ?>
                        <p class="add_league_text">1 league per user!</p>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model LoginForm */

use common\models\LoginForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="offset-4 col-lg-5">
            <div class="login_background">

                <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div style="color:#0f0f0f;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                    <br>
                    Need new verification email? <?= Html::a('Resend', ['site/resend-verification-email']) ?>
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    <div style="float: right">You don't have an account ?
                        <a href="<?= \yii\helpers\Url::to(['/site/signup']) ?>"><b>Register !</b></a></div></div>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

frontend/views/site/news.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application - News';
?>

<div class="container">
    <h1>NEWS</h1>

    <div class="row">
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
    </div>

    <div class="row">
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
    </div>

    <div class="row">
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
        <div class="col-4 news_field"></div>
    </div>

</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model PasswordResetRequestForm */

use frontend\models\PasswordResetRequestForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <div><a href="<?= \yii\helpers\Url::to(['login']) ?>"><h3><-- Back</h3></a>
        <h1><?= Html::encode($this->title) ?></h1>
        <div class="row">
            <div class="col-lg-5 login_background">
                <p>Please fill out your email. A link to reset password will be sent there.</p>

                <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?></div>
                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model ResetPasswordForm */

use frontend\models\ResetPasswordForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>
    <div><a href="<?= \yii\helpers\Url::to(['login']) ?>"><h3><-- Back</h3></a>
        <div class="row">
            <div class="col-lg-5 login_background">
                <p>Please fill out your email. A verification email will be sent there.</p>

                <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>
                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?></div>
                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model ResetPasswordForm */

use frontend\models\ResetPasswordForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please choose your new password:</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?></div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model SignupForm */

use frontend\models\SignupForm;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <div><a href="<?= \yii\helpers\Url::to(['login']) ?>"><h3><-- Back</h3></a>

        <div class="row">
            <div class="col-lg-5 login_background">
                <p>Please fill out the following fields to signup:</p>

                <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?></div>
                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>